# Generated by Django 4.2.4 on 2023-08-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_supplier_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(to='pharmacy.supplier'),
        ),
    ]
