# Generated by Django 4.2.4 on 2023-08-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_stockalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalert',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
