# Generated by Django 4.2.4 on 2023-08-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
    ]
