# Generated by Django 4.2.4 on 2023-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_cerificate_or_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
