# Generated by Django 4.2.4 on 2023-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_patient_birth_cerificate_or_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.34, max_digits=10),
            preserve_default=False,
        ),
    ]
