# Generated by Django 4.2.4 on 2023-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_stock_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birth_cerificate_or_id',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
