# Generated by Django 4.2.4 on 2023-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_patientnotes_labrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_lab_bill',
            field=models.BooleanField(default=False),
        ),
    ]
