# Generated by Django 4.2.4 on 2023-09-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_sale_is_lab_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='lab_request_details',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patient'),
        ),
    ]
