# Generated by Django 4.2.4 on 2023-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_no',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
