# Generated by Django 4.2.4 on 2023-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0026_remove_patient_patient_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
