# Generated by Django 4.2.4 on 2023-10-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0028_patient_pnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pnumber',
        ),
    ]
